name: Static Analysis
on: [pull_request, workflow_dispatch]
jobs:
  diffuse:
    name: Diffuse AAR Analysis
    runs-on: macOS-11
    steps:
      # Set up environment to assemble SDK
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # Assemble artifacts from main branch
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Assemble Release AAR on Main Branch
        run: ./gradlew clean assembleRelease
      - name: Upload Main Branch Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main-aar
          path: |
            BraintreeCore/build/outputs/aar/BraintreeCore-release.aar
            Card/build/outputs/aar/Card-release.aar
      # Assemble artifacts from current branch
      - name: Checkout Current Branch
        uses: actions/checkout@v2
      - name: Assemble Release AAR on Current Branch
        run: ./gradlew clean assembleRelease
      - name: Upload Current Branch Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: current-aar
          path: |
            BraintreeCore/build/outputs/aar/BraintreeCore-release.aar
            Card/build/outputs/aar/Card-release.aar
      # Set up Diffuse
      - name: Install Diffuse
        run: brew install JakeWharton/repo/diffuse
      - name: Download Workflow Artifacts 
        uses: actions/download-artifact@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Run Diffuse analysis
      - name: Run Diffuse Analysis - BraintreeCore
        run: diffuse diff --aar main-aar/BraintreeCore/build/outputs/aar/BraintreeCore-release.aar current-aar/BraintreeCore/build/outputs/aar/BraintreeCore-release.aar
      - name: Run Diffuse Analysis - Card
        run: diffuse diff --aar main-aar/Card/build/outputs/aar/Card-release.aar current-aar/Card/build/outputs/aar/Card-release.aar

